### ISSUE TITLE
Update README.md with your valuable input

### ISSUE THREAD

**Issue by divyankkarolia97** [divyankkarolia97/touch_type#1]

**Comment by manaswinidas** [comment]
@divyankkarolia97 Can you give details regarding this?

**Comment by Leocardoso94** [comment]
#2 
I put more information on readme.md

**Comment by divyankkarolia97** [comment]
@manaswinidas i opened this issue for a friend of mine to get versed with pull request, although thank you and i would love to see your valuable input too. Happy HacktoberFest :+1:
